---
- name: Validate required variables are set
  run_once: true
  assert:
    that:
      - "{{ item }} is defined"
      - "{{ item }} | length > 0"
    quiet: true
    fail_msg: "Required variable {{ item }} undefined or zero length"
  loop:
    - xcode_install_user
    - xcode_install_pass
    - xcode_versions

- name: Check for xcversion
  command: xcversion --version
  ignore_errors: true
  register: xcversion_exists

- name: Set facts
  set_fact:
    should_install_xcversion: "{{ xcversion_exists.rc > 0 }}"
