name: CI
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: [ubuntu-latest]
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Create ansible.cfg for test
        run: "printf '[defaults]\nroles_path=../' >ansible.cfg"
      - name: Run test
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
      - name: Bump release version/tag
        uses: docker://ghcr.io/codfish/semantic-release-action:v1
        # with:
        #   branches: |
        #     [ 'main' ]
        #   plugins: |
        #     [
        #       ["@semantic-release/commit-analyzer", {
        #         "preset": "angular",
        #         "releaseRules": [
        #           {"type": "major", "release": "major"},
        #           {"type": "minor", "release": "minor"},
        #           {"type": "patch", "release": "patch"}
        #         ],
        #       }],
        #       "@semantic-release/commit-analyzer"
        #     ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish role
        run: ansible-galaxy role import --token ${{ secrets.ANSIBLE_GALAXY_TOKEN }} nick-invision $(basename `git rev-parse --show-toplevel`)
